version: "3"
services:
  
  react-email-app:
   build:
      context: ./MailClient
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: email-app
   networks:
    -  email-stack-net
   volumes:
    -  ./MailClient/src:/usr/app/src
    -  ./MailClient/public:/usr/app/public
   depends_on:
    - email-server
   stdin_open: true
   tty: true

  email-server:
   build:
      context: ./Server
      dockerfile: Dockerfile.dev
   ports:
     - 4000:4000
   container_name: email-api
   networks:
     - email-stack-net
   volumes:
    - ./Server/src:/usr/app/src
   
    
networks:
  email-stack-net:
    driver: bridge

  