export const IMAP_GETALLMAIL = 'IMAP_GETALLMAIL';

export const IMAP_GETONEMAIL = 'IMAP_GETONEMAIL';

export const POP3_GETALLMAIL = 'POP3_GETALLMAIL';

export const POP3_GETONEMAIL = 'POP3_GETONEMAIL';